
import React, { useState } from 'react';
import { Play, Database, AlertTriangle, CheckCircle, Loader2 } from 'lucide-react';
import { executeAdminSql } from '../../services/api';

export const DatabaseAdmin: React.FC = () => {
    const [query, setQuery] = useState('');
    const [result, setResult] = useState<any>(null);
    const [error, setError] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);

    const handleRun = async () => {
        if (!query.trim()) return;
        setLoading(true);
        setResult(null);
        setError(null);
        try {
            const res = await executeAdminSql(query);
            if (res.status === 'success') {
                setResult(res.data);
            } else {
                setError(res.message || 'Unknown error occurred');
            }
        } catch (e: any) {
            setError(e.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="space-y-6 animate-in fade-in duration-300">
            <div>
                <h3 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
                    <Database className="text-blue-500" size={20} />
                    Database Admin Console
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                    Execute raw SQL queries to create, edit, or manage Supabase tables directly.
                    <br/>
                    <span className="text-red-500 font-bold text-xs uppercase">Warning: This action cannot be undone.</span>
                </p>
            </div>

            <div className="flex flex-col gap-2">
                <textarea
                    className="w-full h-64 bg-slate-900 text-green-400 font-mono text-sm p-4 rounded-xl border border-gray-700 focus:border-blue-500 outline-none resize-none"
                    placeholder="CREATE TABLE example (id bigint generated by default as identity primary key, name text);"
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    spellCheck={false}
                />
                <div className="flex justify-end">
                    <button
                        onClick={handleRun}
                        disabled={loading || !query.trim()}
                        className="bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white px-6 py-2 rounded-lg font-bold flex items-center gap-2 transition-all shadow-lg"
                    >
                        {loading ? <Loader2 size={16} className="animate-spin" /> : <Play size={16} fill="currentColor" />}
                        Run Query
                    </button>
                </div>
            </div>

            {error && (
                <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 p-4 rounded-xl flex items-start gap-3">
                    <AlertTriangle size={20} className="shrink-0 mt-0.5" />
                    <div>
                        <div className="font-bold text-sm">Execution Error</div>
                        <pre className="text-xs mt-1 whitespace-pre-wrap font-mono">{error}</pre>
                    </div>
                </div>
            )}

            {result && (
                <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 text-green-700 dark:text-green-400 p-4 rounded-xl space-y-2">
                    <div className="flex items-center gap-2 font-bold text-sm">
                        <CheckCircle size={18} /> Query Executed Successfully
                    </div>
                    {JSON.stringify(result) !== '[]' && JSON.stringify(result) !== '{}' && (
                        <div className="bg-white dark:bg-black/50 p-3 rounded-lg border border-green-200 dark:border-green-900/50">
                            <pre className="text-xs font-mono overflow-x-auto text-gray-800 dark:text-gray-300">
                                {JSON.stringify(result, null, 2)}
                            </pre>
                        </div>
                    )}
                </div>
            )}
        </div>
    );
};
